"""Add UsageLog for leak detection

Revision ID: 1325a60924ad
Revises: 38c4ea945aa5
Create Date: 2025-07-26 14:14:12.315245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1325a60924ad'
down_revision = '38c4ea945aa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usage_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meter_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('flow_liters', sa.Float(), nullable=False),
    sa.Column('balance_at_time', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['meter_id'], ['meter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usage_log')
    # ### end Alembic commands ###
